spring.datasource.url=jdbc:postgresql://ep-lively-band-a84vm4jt-pooler.eastus2.azure.neon.tech/neondb?sslmode=require&channelBinding=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_46QRlWSZGpNE